### ISSUE TITLE
Low performance over big data amount

### ISSUE THREAD

**Issue by mleczakm** [pharako/mysql-dbal#8]
Making `array_merge` in loop results in exponentially increasing computational complexity. I've implemented fix already https://github.com/paruwa/mysql-dbal/commit/a245d0520c76a6b0cbcff8cff6335fd8634168ae (same is needed for inserting) but didn't find time for creating proper PR.

**Comment by claudiobizzotto** [comment]
Thanks, @mleczakm. Please open the PR when you're ready, so that I can run the test units against it.

**Comment by mleczakm** [comment]
@claudiobizzotto done :)
